# Automatically generated by configure - do not modify
include ../config-host.mak
TARGET_ARCH=arm
TARGET_WORDS_BIGENDIAN=yes
CONFIG_USER_ONLY=yes
CONFIG_LINUX_USER=yes
TARGET_XML_FILES= /usr/src/xen_build_from_xen_source/xen-4.1.2/tools/ioemu-qemu-xen/gdb-xml/arm-core.xml /usr/src/xen_build_from_xen_source/xen-4.1.2/tools/ioemu-qemu-xen/gdb-xml/arm-vfp.xml /usr/src/xen_build_from_xen_source/xen-4.1.2/tools/ioemu-qemu-xen/gdb-xml/arm-vfp3.xml /usr/src/xen_build_from_xen_source/xen-4.1.2/tools/ioemu-qemu-xen/gdb-xml/arm-neon.xml
CONFIG_SOFTFLOAT=yes
TARGET_HAS_BFLT=yes
