# Automatically generated by configure - do not modify
include ../config-host.mak
TARGET_ARCH=ppc64
TARGET_ABI_DIR=ppc
TARGET_WORDS_BIGENDIAN=yes
CONFIG_SOFTMMU=yes
TARGET_XML_FILES= /usr/src/xen_build_from_xen_source/xen-4.1.2/tools/ioemu-qemu-xen/gdb-xml/power64-core.xml /usr/src/xen_build_from_xen_source/xen-4.1.2/tools/ioemu-qemu-xen/gdb-xml/power-fpu.xml /usr/src/xen_build_from_xen_source/xen-4.1.2/tools/ioemu-qemu-xen/gdb-xml/power-altivec.xml /usr/src/xen_build_from_xen_source/xen-4.1.2/tools/ioemu-qemu-xen/gdb-xml/power-spe.xml
CONFIG_SOFTFLOAT=yes
